name: STU3 Firely Terminal Validation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "main", "14-QA" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Validate all resources using Firely Terminal 
  CI_FHIR_VALIDATION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      # Install .NET runtime
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      
      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'
        
      - name: Firely.Terminal (GitHub Actions)
        uses: FirelyTeam/firely-terminal-pipeline@v0.7.18
        with:
          PATH_TO_CONFORMANCE_RESOURCES: input/resources
          PATH_TO_EXAMPLES: input/resources
          #PATH_TO_QUALITY_CONTROL_RULES: unittest
          DOTNET_VALIDATION_ENABLED: true
          JAVA_VALIDATION_ENABLED: true
          JAVA_VALIDATION_OPTIONS: >
            -allow-example-urls true
            -output validation.json
            -html-output validation.html
            -show-message-ids
            -language nl
            -jurisdiction nl
            -sct nl
            -display-issues-are-warnings
            -advisor-file validator/advisor.json
            -resolution-context file:fsh-generated/resources/
          EXPECTED_FAILS: VALIDATION_CONFORMANCE_DOTNET VALIDATION_CONFORMANCE_JAVA VALIDATION_EXAMPLES_JAVA
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
          SUSHI_ENABLED: false
          FIRELY_TERMINAL_VERSION: 3.5.0-beta-1
          ##JAVA_VALIDATOR_VERSION: 6.7.1
          
      - name: Upload validation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fhir-validation-results
          path: |
            validation.json
            validation.html
          retention-days: 1

      - name: Convert Validation Report
        uses: patrick-werner/validation-outcome-markdown-renderer@1.2.1
        with:
          bundle-file: validation.json
          include: errors
          filters: |
            # Struktur: fileName|messageId|detailsWildcard|location


      # - name: Add & Commit
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: 'fsh-generated/resources/'